-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
INSERT INTO academic_programmes(id, name) VALUES
(40, 'ANTROPOLOGIA'),
(41, 'ARTES PLASTICAS'),
(42, 'CIENCIAS DE LA COMPUTACION'),
(43, 'CINE Y TELEVISION'),
(44, 'DISEÑO GRAFICO'),
(45, 'DISEÑO INDUSTRIAL'),
(46, 'FILOLOGIA'),
(47, 'ESTADISTICAS'),
(48, 'FISICA'),
(49, 'FONOAUDIOLOGIA'),
(50, 'GEOGRAFIA'),
(51, 'INGENIERIA AGRICOLA'),
(52, 'INGENIERIA AGRONOMICA'),
(53, 'MEDICINA VETERINARIA'),
(54, 'MUSICA'),
(55, 'NUTRICION'),
(56, 'SOCIOLOGIA'),
(57, 'ZOOTECNIA'),
(58, 'INGENIERIA BIOLOGICA'),
(59, 'CONSTRUCCION'),
(60, 'INGENIERIA ADMINISTRATIVA'),
(61, 'INGENIERIA DE CONTROL'),
(62, 'INGENIERIA DE MINAS'),
(63, 'INGENIERIA DE PETROLEOS'),
(64, 'INGENIERIA FISICA'),
(65, 'INGENIERIA FORESTAL'),
(66, 'INGENIERIA GEOLOGICA');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
DELETE FROM academic_programmes WHERE id >= 40 AND id <= 66;
-- +goose StatementEnd
