-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
SELECT 'up SQL query';
INSERT INTO academic_offers(UNIVERSITY_ID, AP_ID, NAME) VALUES 
(1, 1, 'ADMINISTRACION DE EMPRESAS DIURNA'),
(1, 1, 'ADMINISTRACION DE EMPRESAS NOCTURNA'),
(1, 2, 'ADMINISTRACION INDUSTRIAL'),
(1, 3, 'BIOLOGIA'),
(1, 4, 'COMUNICACION SOCIAL'),
(1, 5, 'CONTADURIA PUBLICA DIURNA'),
(1, 5, 'CONTADURIA PUBLICA NOCTURNA'),
(1, 6, 'DERECHO'),
(1, 7, 'ECONOMIA'),
(1, 8, 'ENFERMERIA'),
(1, 9, 'FILOSOFIA'),
(1, 10, 'HISTORIA'),
(1, 11, 'INGENIERIA CIVIL'),
(1, 14, 'INGENIERIA DE ALIMENTOS'),
(1, 12, 'INGENIERIA DE SISTEMAS'),
(1, 13, 'INGENIERIA QUIMICA'),
(1, 15, 'LICENCIATURA EN EDUCACION CON ENFASIS EN CIENCIAS SOCIALES Y AMBIENTALES'),
(1, 16, 'LICENCIATURA EN EDUCACION INFATIL'),
(1, 17, 'LINGUISTICA Y LITERATURA'),
(1, 18, 'MATEMATICAS'),
(1, 19, 'ODONTOLOGIA'),
(1, 20, 'PROFESIONAL UNIVERSITARIO EN LENGUAS EXTRANJERAS'),
(1, 21, 'QUIMICA'),
(1, 22, 'QUIMICA FARMACEUTICA'),
(1, 23, 'TRABAJO SOCIAL');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
