-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
INSERT INTO academic_offers(university_id, ap_id, name) VALUES
(3, 25, 'TECNOLOGIA EN GESTION DE MARKETING'),
(3, 2, 'ADMINISTRACION EN SEGURIDAD Y SALUD EN EL TRABAJO'),
(3, 11, 'INGENIERIA CIVIL'),
(3, 32, 'TECNOLOGIA EN PRODUCCION INDUSTRIAL'),
(3, 2, 'TECNOLOGIA EN SEGURIDAD E HIGIENE OCUPACIONAL'),
(3, 32, 'TECNOLOGIA EN CONTROL DE CALIDAD'),
(3, 36, 'TECNOLOGIA EN GESTION AMBIENTAL INDUSTRIAL'),
(3, 38, 'TECNOLOGIA EN OPERACIONES DE PLANTAS Y PROCESOS INDUSTRIALES'),
(3, 33, 'TECNOLOGIA EN CONTROL ELECTRONICO DE PROCESOS'),
(3, 12, 'TECNOLOGIA EN DESARROLLO DE SOFTWARE'),
(3, 12, 'TECNOLOGIA EN GESTION DE REDES Y SEGURIDAD INFORMATICA'),
(3, 32, 'INGENIERIA INDUSTRIAL'),
(3, 6, 'DERECHO'),
(3, 26, 'PSICOLOGIA'),
(3, 23, 'TRABAJO SOCIAL'),
(3, 1, 'TECNOLOGIA EN GESTION TURISTICA Y HOTELERA'),
(3, 1, 'TECNOLOGIA EN GESTION LOGISTICA Y PORTUARIA'),
(3, 28, 'TECNOLOGIA EN GESTION DE NEGOCIOS INTERNACIONALES'),
(3, 1, 'TECNOLOGIA EN GESTION FINANCIERA'),
(3, 5, 'TECNOLOGIA EN GESTION CONTABLE'),
(3, 5, 'CONTADURIA PUBLICA'),
(3, 38, 'INGENIERIA DE PROCESOS'),
(3, 12, 'INGENIERIA DE SISTEMAS'),
(3, 1, 'ADMINISTRACION DE EMPRESAS'),
(3, 33, 'INGENIERIA ELECTRONICA'),
(3, 36, 'INGENIERIA AMBIENTAL');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
DELETE FROM academic_offers WHERE university_id = 3;
-- +goose StatementEnd
