-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
INSERT INTO academic_offers(university_id, ap_id, name) VALUES
(4, 34, 'TECNOLOGIA EN MANTENIMIENTO ELECTRICO'),
(4, 33, 'TECNOLOGIA EN MANTENIMIENTO ELECTRONICO'),
(4, 31, 'TECNOLOGIA EN MANTENIMIENTO MECANICO'),
(4, 55, 'GASTRONOMIA'),
(4, 11, 'INGENIERIA CIVIL'),
(4, 52, 'INGENIERIA AGROINDUSTRIAL'),
(4, 26, 'PSICOLOGIA'),
(4, 6, 'DERECHO'),
(4, 12, 'INGENIERIA DE SISTEMAS'),
(4, 67, 'OPTOMETRIA'),
(4, 19, 'ODONTOLOGIA'),
(4, 55, 'NUTRICION Y DIETA'),
(4, 8, 'ENFERMERIA'),
(4, 28, 'ADMINISTRACION DE NEGOCIOS INTERNACIONALES'),
(4, 1, 'ADMINISTRACION DE EMPRESAS TURISTICAS Y HOTELERAS'),
(4, 69, 'TECNOLOGIA EN PRODUCCION Y CREACION DE MODA'),
(4, 5, 'CONTADURIA PUBLICA'),
(4, 70, 'BIOLOGIA MARINA'),
(4, 32, 'INGENIERIA INDUSTRIAL');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
DELETE FROM academic_offers WHERE university_id = 4;
-- +goose StatementEnd
